queue_rules:
  - name: default
    merge_conditions:
      - check-success=deploy
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|auto-merge|dependencies
    actions:
      queue:
